dataset:
  name: ODE_Lorenz
  pair_id: 'all'

model:
  name: PINN
  learning_rate: 0.001
  epochs: 3000
  num_of_layers: 4
  num_of_neurons: 40
  num_of_boundary_points: 800
  num_of_domain_points: 800