dataset:
  name: ODE_Lorenz
  pair_id: 'all'

model:
  name: PINN
  learning_rate: 0.001
  epochs: 3000
  num_of_layers: 5
  num_of_neurons: 50
  num_of_boundary_points: 200
  num_of_domain_points: 50